#!/usr/bin/env bash

DOWNLOAD_DATE=${DOWNLOAD_DATE:-$(date +%Y%m%d)}
RUN_AS=


install_me() {
    if grep "^ID=arch" /etc/*-release >/dev/null 2>&1; then
        INSTALL_TARGET=/usr/local/bin/xfce-test
        echo "I might need the sudo password for installation..."
        RUN_AS="sudo"
    else
        INSTALL_TARGET=~/.local/bin/xfce-test
        mkdir -p ~/.local/bin
    fi
    # bash autocomplete
    BASH_COMPLETION="#begin-xfce-test
_xfce-test_completions()
{
  COMPREPLY=(\$(compgen -W \"${WORK_MODES[*]}\" \"\${COMP_WORDS[1]}\"))
}

complete -F _xfce-test_completions xfce-test
#end-xfce-test
"
    if [ ! -f ~/.bash_completion ]; then
        echo "$BASH_COMPLETION" >> ~/.bash_completion
    else
        if grep "#begin-xfce-test" ~/.bash_completion > /dev/null; then
            sed -i "/#begin-xfce-test/,/#end-xfce-test/d" ~/.bash_completion
        fi
        echo "$BASH_COMPLETION" >> ~/.bash_completion
    fi

    # "fall back"
    $RUN_AS cp $0 ${INSTALL_TARGET}

    echo "Trying to get the latest version"
    $RUN_AS curl -o ${INSTALL_TARGET} https://raw.githubusercontent.com/schuellerf/xfce-test/master/xfce-test || echo "... well I tried to."
    $RUN_AS chmod u+x ${INSTALL_TARGET}

    echo "Installed 'xfce-test' to $(readlink -f ${INSTALL_TARGET})"
    echo "You can just call it with 'xfce-test'"
}

usage() {
    echo "Usage:"
    echo "  $0 [command]"
    echo ""
    echo "  Without a command, interactive mode is started"
    echo ""
    echo "  command:"
    echo "      start          Start the container for testing"
    echo "                     USE THIS IF YOU ARE NOT SURE"
    echo "      pull           Get the latest container"
    echo "      no-session     starts the container without a session"
    echo "                     (this is great if you want to test the session itself ;)"
    echo "      install        Installed the script to ~/.local/bin for"
    echo "                     easier execution"
    echo ""
    echo "  -- Commands doing some automatic stuff"
    echo "      screenshots    Creating just a screenshot of each 'main' xfce app"
    echo "      behave         Run all behave tests"
    echo "      behavevideo    Run all behave tests while recording them"
    echo "      fulltestvideo  Create a demo video - this is the one done by travis"
    echo ""
    echo "  -- Commands only working from within the cloned git repository"
    echo "      build          Builds the container locally"
    echo "                     Environment variable:"
    echo "                     DOWNLOAD_DATE defines if all source code should be"
    echo "                                 newly cloned and rebuilt"
    echo "                     default: ${DOWNLOAD_DATE}"
    echo "  Environment variables:"
    echo "     (useful environment variables you might want to set)"
    echo "      XFSM_VERBOSE   set to \"1\" to get a log file in ~/.xfce4-session.verbose-log"
    echo "                     default: \"${XFSM_VERBOSE}\""
    echo "      LANG           choose language for the session"
    echo "                     default: \"${LANG}\""

}

MANUAL_MODES=("start" "pull" "no-session")
AUTOMATIC_MODES=("screenshots" "behave" "behavevideo" "fulltestvideo")

REPO_MODES=("build")
WORK_MODES=(${MANUAL_MODES[*]} ${AUTOMATIC_MODES[*]})
if git status > /dev/null 2>&1; then
    WORK_MODES+=(${REPO_MODES[*]})
fi

MODES=("install" ${WORK_MODES[*]})


# prepare all available modes in a bash-case syntax
MODES_FOR_CASE=$(IFS=$'|'; echo "${WORK_MODES[*]}")
shopt -s extglob
MODES_FOR_CASE="+($MODES_FOR_CASE)"

if [ -z $TAG ]; then
    TAG=$(git rev-parse --abbrev-ref HEAD 2>/dev/null|tr '/' '_')
    if [[ $TAG != *_* ]]; then
        TAG=latest
    fi
fi

if [ $# -eq 1 ]; then
    case $1 in
        "install")
            install_me
            exit 0
        ;;
        --help|help|-h)
            usage
            exit 0
        ;;
        $MODES_FOR_CASE )
            mode=$1
        ;;
        *)
            echo "Unknown Option '$1'"
            usage
            exit 0
        ;;

    esac

else

    usage

    
    MODES=(${MODES[*]} "tag" "XFSM_VERBOSE" "LANG")

    echo ""
    echo "  -- Commands only for interactive mode"
    echo "      tag          changes docker \"TAG\" to work with (e.g. ubuntu_19.04)"
    echo "                   (only for the current execution of $0)"
    echo "      XFSM_VERBOSE change verbosity of xfce4-session"
    echo "      LANG         change the language for the session (default: $LANG)"
    echo ""

    PS3="Choose option: "
    select mode in ${MODES[@]}; do
        case $mode in
            "install")
                install_me
                exit 0
            ;;
            "tag")
                read -i $TAG -p "Change tag from \"$TAG\" to: " TAG_NEW

                if [ ${#TAG_NEW} -ge 1 ]; then
                    TAG=$TAG_NEW
                    echo "OK - tag changed to \"$TAG\""
                else
                    echo "OK - tag is still \"$TAG\""
                fi
            ;;
            "XFSM_VERBOSE")
                if [ "x${XFSM_VERBOSE}" != "x1" ]; then
                    echo "Enabled debug output..."
                    export XFSM_VERBOSE=1
                else
                    echo "Disabled debug output..."
                    unset XFSM_VERBOSE
                fi
            ;;
            "LANG")
                # getting all languages with title out of the container
                ALL_LANGS="$(docker run --rm schuellerf/xfce-test:$TAG locale -av |
                   while read LINE; do
                      if [[ $LINE =~ ^locale:.* ]]; then
                        LOC=$(echo "$LINE"|grep -Po "(?<=locale: )[^ ]*");
                      fi;
                      if [[ $LINE =~ title ]]; then
                        T=$(echo "$LINE"|grep -Po "(?<=title \| ).*");
                        echo "$LOC ($T)";
                      fi;
                    done)"

                OLD_IFS=${IFS}
                IFS=$'\n'
                select l in ${ALL_LANGS}; do
                  case $l in
                    *) if [ ${#l} -ge 1 ]; then
                        LANG=$(echo $l|grep -Po "^[^ ]+")
                        echo "OK - language changed to \"$LANG\""
                      else
                        echo "OK - language is still \"$LANG\""
                      fi
                    break
                    ;;
                  esac
                  echo "Choose Language:"
                done
                IFS=${OLD_IFS}

            ;;
            *)
                break
            ;;
        esac
        echo "-- Main Menu --"
    done
fi

if [ ${#mode} -ge 1 ]; then
  echo "You are working with the container: $TAG"
else
  echo "Nothing valid selected - exiting"
  exit 1
fi

case $mode in
    "pull")
        docker pull schuellerf/xfce-test:${TAG}
        exit 0
    ;;
    "build")
        echo "DOWNLOAD_DATE is set to ${DOWNLOAD_DATE}"
        docker build --build-arg DOWNLOAD_DATE=${DOWNLOAD_DATE} --tag schuellerf/xfce-test:$TAG .
        # easier to rebuild if we know the DOWNLOAD_DATE
        docker tag schuellerf/xfce-test:$TAG schuellerf/xfce-test:${TAG}-${DOWNLOAD_DATE}
        exit 0
    ;;
esac

# This starts the container for manual or semi automated tests

# resolution of the test X server
# TBD: define what the minimal supported resolution is
export RESOLUTION=1024x768

# use this X display number for the tests
export DISPLAY_NUM=1

# set SCREENSHOTS to ALWAYS to get screenshots during behave tests
export SCREENSHOTS=${SCREENSHOTS:-NONE}

# quit on errors
set +e

# TBD replace by nicer check
if [ -f /etc/lsb-release ] && grep Ubuntu /etc/lsb-release >/dev/null; then
  UBUNTU_PACKAGES="xserver-xephyr docker.io xvfb ffmpeg"

  for package in ${UBUNTU_PACKAGES}; do
    if ! apt list --installed 2>/dev/null|grep "^$package" >/dev/null; then
      echo "I might need the sudo password to install the necessary packages..."
      sudo apt install -y $package
    fi
  done
fi

# kill an already running instance if still running from the last test
killall -q Xephyr

Xephyr :${DISPLAY_NUM} -sw-cursor -softCursor -resizeable -ac -screen ${RESOLUTION} &

docker rm xfce-test 2>/dev/null
echo ""

#default parameters

COMMAND=""
DETACH="--detach"
DOCKER_MODES=""

if [ $mode == "no-session" ]; then
    COMMAND=/bin/bash
    # don't detach:
    DETACH=""
    DOCKER_MODES="--tty --interactive"
fi

DOCKER_MODES="${DOCKER_MODES} --volume /etc/timezone:/etc/timezone"
DOCKER_MODES="${DOCKER_MODES} --volume /etc/localtime:/etc/localtime"

echo -n "Starting container: "
docker run --tty --interactive --name xfce-test $DETACH $DOCKER_MODES \
           --cap-add=SYS_PTRACE \
           --env DISPLAY=":${DISPLAY_NUM}" \
           --env LDTP_DEBUG=2 \
           --env SCREENSHOTS \
           --env RESOLUTION \
           --env XFSM_VERBOSE \
           --env LANG \
           --volume ${PWD}:/data \
           --volume /tmp/.X11-unix:/tmp/.X11-unix:z \
           schuellerf/xfce-test:$TAG $COMMAND

if [ -n $DETACH ]; then
    sleep 3 # give ldtp and the session some time
    if [ $mode == "screenshots" ]; then
        docker exec --tty --interactive xfce-test /container_scripts/make_screenshots.py
    elif [ $mode == "behave" ]; then
        docker exec --tty --interactive xfce-test bash -c "cd /behave_tests; GUI_TIMEOUT=120 behave"
    elif [ $mode == "behavevideo" ]; then
        docker exec --tty --interactive xfce-test /container_scripts/run_behave_recorded.sh
    elif [ $mode == "fulltestvideo" ]; then
        docker exec --tty --interactive xfce-test /container_scripts/full_test_video.sh
    else
        docker exec --tty --interactive xfce-test bash -c 'echo "This container includes:";
            cat ~xfce-test_user/version_info.txt;
            echo "You might want to call \"tmux attach\" if you know what tmux ( https://tmux.github.io ) is and need to go to the internals."'
        docker exec --tty --interactive xfce-test /bin/bash
    fi
fi

# Copy out the debug file if it exists
docker cp xfce-test:/home/xfce-test_user/.xfce4-session.verbose-log . || echo ""

# Tear down
if [ $mode != "no-session" ]; then
    docker exec xfce-test xfce4-session-logout --logout
fi
docker stop xfce-test
docker rm xfce-test
killall -q Xephyr
rm -rf /tmp/.X11-unix/X${DISPLAY_NUM} /tmp/.X${DISPLAY_NUM}-lock

